name: Python application CI 

on:
  push:
    paths:
      - 'app_python/**'
      - '.github/workflows/app_python.yml'
      
jobs:
  build:

    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./app_python
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run Tests 
      run: |
        cd moscow_time
        python manage.py test
    
